name: continuous-integration-foo

on:
    push:
        branches:
            - master

jobs:
    build-and-test:
        runs-on:  ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Build with Gradle!
              working-directory: .
              run: ./gradlew build -x test

            - name: Run tests
              working-directory: .
              run: ./gradlew test

    GitHub Action for pytest:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Docker-Compose
        working-directory: .
        run: docker-compose up -d --build
      - name: Install pytest
        run:
          pip3 install -U requests
          pip3 install pytest
      - name: GitHub Action for pytest
        uses: actions/checkout@v1
        working-directory: .
        with:
          args: pytest
